# Generated by Django 5.0.2 on 2024-02-09 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filosofo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Phrases',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('phrase', models.CharField(max_length=600)),
                ('philosopher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoicApp.filosofo')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.URLField()),
                ('philosopher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoicApp.filosofo')),
            ],
        ),
    ]
